version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: local_pg
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - local_pg_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    container_name: local_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  local_pg_data:

